namespace pvNugsSecretManagerNc10;

/// <summary>
/// Configuration settings for <c>SecretManager</c>, controlling caching behaviour
/// and cache key namespacing.
/// </summary>
/// <remarks>
/// <para><c>Configuration Binding:</c></para>
/// <para>
/// This class is bound from the application configuration system via
/// <see cref="Microsoft.Extensions.Options.IOptions{TOptions}"/>.
/// The expected section name is exposed by <see cref="Section"/> and defaults to
/// <c>PvNugsSecretManagerConfig</c>.
/// </para>
///
/// <para><c>appsettings.json Example:</c></para>
/// <code>
/// {
///   "PvNugsSecretManagerConfig": {
///     "CacheKeyPrefix": "MyApp",
///     "CacheTimeToLive": "1.00:00:00"
///   }
/// }
/// </code>
///
/// <para><c>Dependency Injection Registration:</c></para>
/// <code>
/// services.Configure&lt;PvNugsSecretManagerConfig&gt;(
///     configuration.GetSection(PvNugsSecretManagerConfig.Section));
/// </code>
///
/// <para><c>Defaults:</c></para>
/// <list type="bullet">
/// <item><description>
///   <see cref="CacheKeyPrefix"/> defaults to <c>PvNugsSecretManagerNc10</c>, which is safe
///   for single-application deployments. In multi-application or multi-tenant environments
///   this should be overridden with a unique, application-scoped prefix to avoid cache
///   key collisions.
/// </description></item>
/// <item><description>
///   <see cref="CacheTimeToLive"/> defaults to <c>5 days</c>, which suits long-lived static
///   secrets such as API keys or connection strings. Reduce this value for secrets that
///   rotate frequently or where freshness is critical.
/// </description></item>
/// </list>
///
/// <para><c>Dynamic Credential Note:</c></para>
/// <para>
/// <see cref="CacheTimeToLive"/> applies only to static secrets. Dynamic credentials
/// (<see cref="pvNugsSecretManagerNc10Abstractions.IPvNugsDynamicCredential"/>) are always
/// cached using a TTL derived from their own <c>ExpirationDateUtc</c>, regardless of this setting.
/// </para>
/// </remarks>
/// <seealso cref="pvNugsSecretManagerNc10Abstractions.IPvNugsSecretManager"/>
/// <seealso cref="pvNugsSecretManagerNc10Abstractions.IPvNugsDynamicCredential"/>
public class PvNugsSecretManagerConfig
{
    /// <summary>
    /// The configuration section name used to bind this class from
    /// <c>appsettings.json</c> or other configuration sources.
    /// </summary>
    /// <value>
    /// <c>"PvNugsSecretManagerConfig"</c>
    /// </value>
    /// <example>
    /// <code>
    /// services.Configure&lt;PvNugsSecretManagerConfig&gt;(
    ///     configuration.GetSection(PvNugsSecretManagerConfig.Section));
    /// </code>
    /// </example>
    public const string Section = nameof(PvNugsSecretManagerConfig);

    /// <summary>
    /// Gets or sets the prefix prepended to all cache keys generated by <c>SecretManager</c>.
    /// </summary>
    /// <value>
    /// Defaults to <c>"PvNugsSecretManagerNc10"</c>.
    /// </value>
    /// <remarks>
    /// <para>
    /// Cache keys are built in the format <c>prefix:key1=value1:key2=value2</c>.
    /// The prefix acts as a namespace, preventing collisions with cache entries
    /// written by other components sharing the same cache instance.
    /// </para>
    /// <para>
    /// In multi-application or multi-tenant environments, set this to a value that
    /// uniquely identifies the application or tenant (e.g. <c>"MyApp:Tenant42"</c>).
    /// </para>
    /// </remarks>
    public string CacheKeyPrefix { get; set; } = "PvNugsSecretManagerNc10";

    /// <summary>
    /// Gets or sets the time-to-live applied to cached static secrets.
    /// </summary>
    /// <value>
    /// Defaults to <c>5 days</c> (<c>TimeSpan.FromDays(5)</c>).
    /// </value>
    /// <remarks>
    /// <para>
    /// This TTL is used for entries written by <c>GetStaticSecretAsync</c> and
    /// <c>GetStaticSecretsAsync</c>. Reduce this value when secrets rotate frequently
    /// or when strict freshness guarantees are required.
    /// </para>
    /// <para>
    /// This setting has <b>no effect</b> on dynamic credentials; their cache lifetime
    /// is always derived from <c>IPvNugsDynamicCredential.ExpirationDateUtc</c>.
    /// </para>
    /// <para>
    /// The value is expressed as a <see cref="TimeSpan"/> and may be bound from
    /// configuration using the standard .NET timespan format string, e.g.
    /// <c>"1.00:00:00"</c> for one day or <c>"00:30:00"</c> for thirty minutes.
    /// </para>
    /// </remarks>
    public TimeSpan CacheTimeToLive { get; set; } = TimeSpan.FromDays(5);
}