<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>10.0.0</Version>
        <Authors>Pierre Van Wallendael</Authors>
        <PackageReleaseNotes>initial .NET 10 Hybrid logger implementation.</PackageReleaseNotes>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryType>GitHub</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageProjectUrl>https://github.com/licheez/pvWayNugs.git</PackageProjectUrl>
        <RepositoryUrl>https://github.com/licheez/pvWayNugs.git</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>pvwayLogoTextLess256.png</PackageIcon>
        <Copyright>pvWay Ltd</Copyright>
        <PackageTags>logging, hybrid-logger, multi-target-logging, structured-logging, async-logging, contextual-logging, enterprise-logging, dependency-injection, thread-safe, net10, dotnet, microsoft-extensions-logging, pvnugs, pvnugslogger</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
      <PackageReference Include="pvNugsLoggerNc10Abstractions" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath="\" />
        <None Update="bin/$(Configuration)\$(TargetFramework)\$(AssemblyName).xml">
            <Pack>true</Pack>
            <PackagePath>lib\$(TargetFramework)</PackagePath>
        </None>
      <None Update="pvwayLogoTextLess256.png">
        <Pack>True</Pack>
        <PackagePath>/</PackagePath>
      </None>
    </ItemGroup>

</Project>
