name: vault-lab

services:
  postgres5432:
    image: postgres:latest
    container_name: postgres5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev-only-password
      
  postgres5433:
    image: postgres:latest
    container_name: postgres5433
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: dev-only-password
      
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-only-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: dev-only-password
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
